apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
# images:
# - name: quay.io/upslopeio/next-app
#   newName: quay.io/christian_hufnagel/next-app
#   newTag: bdc9ad410080aec4a5b8efe656511340a0fa4605
commonLabels:
  app.kubernetes.io/instance: next-app
  app.kubernetes.io/name: next-app
